# commands to specify testing environments
language: python
dist: xenial
os: linux
jobs:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial
    - python: 3.9
      dist: xenial
    - python: nightly
      dist: xenial
  allow_failures:
    - python: nightly

branches:
  only:
    - master
    - /^[0-9].+$/

# command to install dependencies
install:
  - pip install -r test-requirements.txt
  - python -m pip install mypy
  - python -m pip install flake8
  - mypy --version

# command to run tests
script:
  - python --version
  - python -m unittest discover nionswift_plugin -v -p '*_test.py'
  - python -m unittest discover nion -v -p '*_test.py'
  - mypy --namespace-packages --ignore-missing-imports --follow-imports=silent nion/eels_analysis/BackgroundModel.py
  - flake8 --max-line-length=160 nion/eels_analysis/BackgroundModel.py
